apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.service.namespace }}
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
  type: {{ .Values.service.type }}